###################################################
# This Dockerfile is used by docker-compose.dev.yml
# to build the development container.
###################################################

FROM node:22-bookworm as dev
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y openssl
WORKDIR /app
CMD ["sh", "./bin/docker-start"]
